version: "3.1"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - "80:80"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge
